# Generated by Django 5.2 on 2025-04-22 23:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('lease_status', models.BooleanField(default=False)),
                ('price', models.FloatField(blank=True, null=True)),
                ('datestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('md5', models.CharField(blank=True, max_length=32, null=True)),
                ('fs_props', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image_hashes', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('last_modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('revision', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('datestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='documentz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('text_contents', models.TextField(blank=True, null=True)),
                ('image_hashes', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('last_modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('revision', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('datestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='report_categories',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cat_description', models.CharField(blank=True, max_length=512, null=True)),
                ('cat_icon', models.CharField(blank=True, max_length=255, null=True)),
                ('datestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.classification')),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('skill', models.CharField(blank=True, max_length=255, null=True)),
                ('frequency', models.IntegerField(blank=True, null=True)),
                ('match_percentage', models.FloatField(blank=True, null=True)),
                ('snippet', models.TextField(blank=True, null=True)),
                ('datestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.classification')),
            ],
        ),
        migrations.CreateModel(
            name='ClassificationSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, max_length=255, null=True)),
                ('datestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.classification')),
            ],
        ),
        migrations.AddField(
            model_name='classification',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.document'),
        ),
        migrations.CreateModel(
            name='lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessee_name', models.CharField(max_length=255)),
                ('lease_start', models.DateField()),
                ('lease_end', models.DateField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
            ],
        ),
        migrations.CreateModel(
            name='reports',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('tree_items', models.CharField(blank=True, max_length=512, null=True)),
                ('html_name', models.CharField(blank=True, max_length=512, null=True)),
                ('model_name', models.CharField(blank=True, max_length=512, null=True)),
                ('report_icon', models.CharField(blank=True, max_length=255, null=True)),
                ('report_view', models.CharField(blank=True, max_length=255, null=True)),
                ('report_image', models.CharField(blank=True, max_length=255, null=True)),
                ('datestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('cat_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_cat', to='assets.report_categories')),
            ],
        ),
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_sim', models.FloatField(blank=True, null=True)),
                ('text_sim', models.FloatField(blank=True, null=True)),
                ('image_sim', models.FloatField(blank=True, null=True)),
                ('semantic_sim', models.FloatField(blank=True, null=True)),
                ('overall_sim', models.FloatField(blank=True, null=True)),
                ('datestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('doc1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similarity_doc1', to='assets.document')),
                ('doc2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similarity_doc2', to='assets.document')),
            ],
            options={
                'db_table': 'assets_similarities',
            },
        ),
        migrations.CreateModel(
            name='similarityz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meta_sim', models.FloatField(blank=True, null=True)),
                ('text_sim', models.FloatField(blank=True, null=True)),
                ('image_sim', models.FloatField(blank=True, null=True)),
                ('overall_sim', models.FloatField(blank=True, null=True)),
                ('datestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('doc1_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sim_as_doc1', to='assets.documentz')),
                ('doc2_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sim_as_doc2', to='assets.documentz')),
            ],
        ),
    ]
