# Generated by Django 5.1.7 on 2025-03-11 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='datestamp',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='lease',
            name='lease_start',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
