# Generated by Django 5.1.7 on 2025-04-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_categories',
            name='cat_description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
