# Generated by Django 5.1.7 on 2025-03-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_datestamp_alter_lease_lease_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='datestamp',
            new_name='datetime',
        ),
    ]
