# Generated by Django 5.1.7 on 2025-03-11 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_rename_datestamp_asset_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='datetime',
            new_name='datestamp',
        ),
        migrations.AddField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lease',
            name='datestamp',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
