# Generated by Django 5.1.7 on 2025-03-25 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_rename_datetime_asset_datestamp_asset_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('created_date', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image_hashes', models.TextField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('last_modified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('revision', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='asset',
            name='datestamp',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='description',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='datestamp',
        ),
        migrations.AlterField(
            model_name='asset',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lease',
            name='lease_start',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Similarityz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_sim', models.FloatField(blank=True, null=True)),
                ('text_sim', models.FloatField(blank=True, null=True)),
                ('image_sim', models.FloatField(blank=True, null=True)),
                ('overall_sim', models.FloatField(blank=True, null=True)),
                ('doc1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similarities_as_doc1', to='assets.documentz')),
                ('doc2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similarities_as_doc2', to='assets.documentz')),
            ],
        ),
    ]
