# Generated by Django 5.1.7 on 2025-03-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_documentz_remove_asset_datestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentz',
            name='temp_field',
            field=models.CharField(default='temp', max_length=10),
        ),
    ]
