# Generated by Django 5.1.7 on 2025-03-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_documentz_temp_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentz',
            name='temp_field',
        ),
    ]
