# Generated by Django 5.1.7 on 2025-03-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_alter_similarityz_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentz',
            name='temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='similarityz',
            name='temp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
