# Generated by Django 5.1.7 on 2025-03-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_documentz_temp_similarityz_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentz',
            name='temp',
        ),
        migrations.RemoveField(
            model_name='similarityz',
            name='temp',
        ),
    ]
