# Generated by Django 5.1.7 on 2025-03-25 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_alter_similarityz_doc1_alter_similarityz_doc2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='similarityz',
            old_name='doc1',
            new_name='doc1_id',
        ),
        migrations.RenameField(
            model_name='similarityz',
            old_name='doc2',
            new_name='doc2_id',
        ),
    ]
