# Generated by Django 5.1.7 on 2025-03-26 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_rename_doc1_similarityz_doc1_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentz',
            old_name='text',
            new_name='text_contents',
        ),
    ]
