# Generated by Django 5.1.7 on 2025-04-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_report_categories_asset_datestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report_categories',
            old_name='description',
            new_name='cat_description',
        ),
        migrations.RenameField(
            model_name='report_categories',
            old_name='name',
            new_name='cat_icon',
        ),
        migrations.RenameField(
            model_name='report_categories',
            old_name='id',
            new_name='cat_id',
        ),
        migrations.RenameField(
            model_name='reports',
            old_name='id',
            new_name='report_id',
        ),
        migrations.AddField(
            model_name='report_categories',
            name='cat_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reports',
            name='report_icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reports',
            name='report_view',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reports',
            name='tree_items',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
