# Generated by Django 5.1.7 on 2025-04-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0016_rename_description_report_categories_cat_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='report_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
