# Generated by Django 5.1.7 on 2025-04-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_reports_report_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='test',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
