# Generated by Django 5.1.7 on 2025-04-03 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0018_reports_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reports',
            name='test',
        ),
    ]
