# Generated by Django 5.1.7 on 2025-04-21 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classification',
            name='document',
        ),
        migrations.RemoveField(
            model_name='classificationskill',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='classificationcategory',
            name='classification',
        ),
        migrations.RemoveField(
            model_name='similarity',
            name='doc2',
        ),
        migrations.RemoveField(
            model_name='similarity',
            name='doc1',
        ),
        migrations.RemoveField(
            model_name='reports',
            name='cat_id',
        ),
        migrations.RenameField(
            model_name='documentz',
            old_name='text_contents',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='datestamp',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='price',
        ),
        migrations.RemoveField(
            model_name='documentz',
            name='datestamp',
        ),
        migrations.RemoveField(
            model_name='lease',
            name='datestamp',
        ),
        migrations.RemoveField(
            model_name='similarityz',
            name='datestamp',
        ),
        migrations.RemoveField(
            model_name='similarityz',
            name='doc1_id',
        ),
        migrations.RemoveField(
            model_name='similarityz',
            name='doc2_id',
        ),
        migrations.AddField(
            model_name='similarityz',
            name='doc1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similarities_as_doc1', to='dashboard.documentz'),
        ),
        migrations.AddField(
            model_name='similarityz',
            name='doc2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='similarities_as_doc2', to='dashboard.documentz'),
        ),
        migrations.AlterField(
            model_name='documentz',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='similarityz',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='ClassificationDetail',
        ),
        migrations.DeleteModel(
            name='ClassificationSkill',
        ),
        migrations.DeleteModel(
            name='Classification',
        ),
        migrations.DeleteModel(
            name='ClassificationCategory',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Similarity',
        ),
        migrations.DeleteModel(
            name='report_categories',
        ),
        migrations.DeleteModel(
            name='reports',
        ),
    ]
