# Generated by Django 5.1.7 on 2025-03-25 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Document',
            new_name='Documentz',
        ),
        migrations.RenameModel(
            old_name='Similarity',
            new_name='Similarityz',
        ),
    ]
